# 4. Linear Regression

Linear regression as a model is interpretable. Get a number for each feature that directly represents how that feature influences the target (dependent variable). If the coefficient is larger, it potentially means that the variable has a larger impact both directly (positive) or inversely (negative) to a large degree.

Linear regression first estimates a baseline value called the intercept, then estimates a multiplicative coefficient for each feature. Summing the baseline and all the coefficient-transformed features, to get the final prediction.

Makes it __accessible to general interpretation__ by inspection of a weights vector

# Linear regression with TensorFlow

TensorFlow achieves the result in iteratively, gradually learning the best linear regression parameters that will minimize the loss.

`tf.estimators` is an API that has pre-made specific procedures to simplify training, evaluation, predicting and the exporting of models (e.g regression models or basic neural networks). Easily deployed on any hardware or on distributed multi-server environments without much code changes

## Development with Estimators

4 steps involved in developing an Estimator model:
1. Acquire data using `tf.data` functions
2. Instantiate the feature columns
3. Instantiate and train the Estimator
4. Evaluate the model's performance

Below will loop through batches of data points and let TensorFlow update the slope and y intercept. Using the _Boston Housing_ dataset. Create a regression Estimator in TensorFlow using Keras functions

In [16]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

# Get the Boston Housing dataset
housing_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
path = tf.keras.utils.get_file(housing_url.split('/')[-1], housing_url)
columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_table(
	path,
	delim_whitespace=True,
	header=None,
	names=columns
)
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [2]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677082,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [17]:
# Splitting Training and Testing Data
np.random.seed(1)
train = data.sample(frac=0.8).copy()
y_train = train['MEDV']
train.drop('MEDV', axis=1, inplace=True)
test = data.loc[~data.index.isin(train.index)].copy()
y_test = test['MEDV']
test.drop('MEDV', axis=1, inplace=True)

In [14]:
learning_rate = 0.05
def make_input_fn(data_df, label_df, num_epochs=10, shuffle=True, batch_size=256):
	''' function creates a tf.data dataset from a pandas DataFrame turning into a Python
		dictionary of pandas Series. Also provides batch size definitions and random shuffling
	'''
	def input_function():
		ds = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))
		if shuffle:
			ds = ds.shuffle(1000)
		ds = ds.batch(batch_size).repeat(num_epochs)
		print(ds)
		return ds

	return input_function

def define_feature_column(data_df, categorical_cols, numeric_cols):
    '''function that maps each column name to a specific tf.feature_column transformation
       offering functions that can process any kind of data
       
       numeric: numeric_column
       categorical: cateorical_column_with_vocabulary_list
    '''
    feature_columns = []
    for feature_name in numeric_cols:
        feature_columns.append(tf.feature_column.numeric_column(
			feature_name,
			dtype=tf.float32
		))
    
    for feature_name in categorical_cols:
        vocabulary = data_df[feature_name].unique()
        feature_columns.append(tf.feature_column.categorical_column_with_vocabulary_list(
			feature_name,
			vocabulary
		))

    return feature_columns

def canned_keras(model, output_dir=None):
    if output_dir is None:
        model_dir = tempfile.mkdtemp()
    else:
        model_dir = output_dir
    keras_estimator = tf.keras.estimator.model_to_estimator(
		keras_model=model,
		model_dir=model_dir, 
		config=tf.estimator.RunConfig().replace(save_summary_steps=100)
	)
    return keras_estimator

In [21]:
# Declare the different data types for each column
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']

# Define the feature columns using the above functions
feature_columns = define_feature_column(data, categorical_cols, numeric_cols)
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)

# Define the model
output_dir = './logs/LinearRegressor_1'
linear_est = tf.estimator.LinearRegressor(
	feature_columns=feature_columns,
	model_dir=output_dir,
	config=tf.estimator.RunConfig().replace(save_summary_steps=100)
)

# Train the model
linear_est.train(train_input_fn)
result = linear_est.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using config: {'_model_dir': './logs/LinearRegressor_1', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/LinearRegressor_1\model.ckpt-2800
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\training\saver.py:1077: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 2800...
INFO:tensorflow:Saving checkpoints for 2800 into ./logs/LinearRegressor_1\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 2800...
INFO:tensorflow:loss = 30.238426, step = 2800
INFO:tensorflow:global_step/sec: 123.857
INFO:tensorflow:loss = 27.40481, step = 2900 (0.809 sec)
INFO:tensorflow:global_step/sec: 150.15
INFO:tensorflow:loss = 31.936356, step = 3000 (0.666 sec)
INFO:tensorflow:global_step/sec: 143.267
INFO:tensorflow:loss = 28.032257, step = 3100 (0.697 sec)
INFO:tensorflow:global_step/sec: 149.031
INFO:tensorflow:loss = 30.30122, step = 3200 (0.672 sec)
INFO:tensorflow:global_step/sec: 154.083
INFO:tensorflow:loss = 29.105776, step = 3300 (0.649 sec)
INFO:tensorflow:global_step/sec: 155.763
INFO:tensorflow:loss = 33.11467, step = 3400 (0.642 sec)
INFO:tensorflow:global_step/sec: 153.61
INFO:tensorflow:loss = 28.72005, step = 3500 (0.650 sec)
INFO:tensorflow:global_step/sec: 153.61
INFO:tensorflow:loss = 29.481197, step = 3600 (0.651 sec)
INFO:tensorflow:global_step/sec: 156.494
INFO:tensorflow:loss = 26.824724, step = 3700 (0.639 sec)
INFO:tensorflow:global_step/sec: 156.25
INFO:tensorflow:loss = 26.504364, step = 3800 (0.641 sec)
INFO:tensorflow:global_step/sec: 153.375
INFO:tensorflow:loss = 27.922447, step = 3900 (0.651 sec)
INFO:tensorflow:global_step/sec: 154.321
INFO:tensorflow:loss = 27.54168, step = 4000 (0.648 sec)
INFO:tensorflow:global_step/sec: 153.139
INFO:tensorflow:loss = 23.627808, step = 4100 (0.653 sec)
INFO:tensorflow:global_step/sec: 154.552
INFO:tensorflow:loss = 29.147575, step = 4200 (0.647 sec)
INFO:tensorflow:global_step/sec: 156.013
INFO:tensorflow:loss = 28.311415, step = 4300 (0.641 sec)
INFO:tensorflow:global_step/sec: 156.25
INFO:tensorflow:loss = 29.510317, step = 4400 (0.641 sec)
INFO:tensorflow:global_step/sec: 154.799
INFO:tensorflow:loss = 24.823961, step = 4500 (0.646 sec)
INFO:tensorflow:global_step/sec: 153.61
INFO:tensorflow:loss = 24.509949, step = 4600 (0.650 sec)
INFO:tensorflow:global_step/sec: 155.038
INFO:tensorflow:loss = 28.663984, step = 4700 (0.645 sec)
INFO:tensorflow:global_step/sec: 152.439
INFO:tensorflow:loss = 30.435558, step = 4800 (0.656 sec)
INFO:tensorflow:global_step/sec: 151.745
INFO:tensorflow:loss = 27.959208, step = 4900 (0.659 sec)
INFO:tensorflow:global_step/sec: 153.846
INFO:tensorflow:loss = 30.035515, step = 5000 (0.651 sec)
INFO:tensorflow:global_step/sec: 153.375
INFO:tensorflow:loss = 26.552097, step = 5100 (0.651 sec)
INFO:tensorflow:global_step/sec: 154.559
INFO:tensorflow:loss = 27.305714, step = 5200 (0.648 sec)
INFO:tensorflow:global_step/sec: 153.375
INFO:tensorflow:loss = 21.921564, step = 5300 (0.651 sec)
INFO:tensorflow:global_step/sec: 152.905
INFO:tensorflow:loss = 29.216713, step = 5400 (0.655 sec)
INFO:tensorflow:global_step/sec: 154.559
INFO:tensorflow:loss = 26.972584, step = 5500 (0.646 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5600...
INFO:tensorflow:Saving checkpoints for 5600 into ./logs/LinearRegressor_1\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5600...
INFO:tensorflow:Loss for final step: 25.929752.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-13T23:13:30Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/LinearRegressor_1\model.ckpt-5600
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.39696s
INFO:tensorflow:Finished evaluation at 2022-06-13-23:13:31
INFO:tensorflow:Saving dict for global step 5600: average_loss = 30.171392, global_step = 5600, label/mean = 22.048513, loss = 30.171392, prediction/mean = 21.20843
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5600: ./logs/LinearRegressor_1\model.ckpt-5600
{'average_loss': 30.171392, 'label/mean': 22.048513, 'loss': 30.171392, 'prediction/mean': 21.20843, 'global_step': 5600}

Estimator sifts the data from the data functions and converts the data into proper form based on the matched feature name and `tf.feature_column` function does the entire job.

Optimal line found by Estimator might not be the line of best fit. Depends on the number of iterations, learning rate, loss function and other hyperparameters of the algorithm. Observe the loss function over time to help troubleshoot problems

### Extensions
 
__Combining 2 variables__

A combination between 2 variables can explain the target better than the features taken singularly. The combination could capture an underlying component of the prediction that individually the variables cannot explain. Using `tf.feature_column_.crossed_column` function can automatically allow Estimator to receive the output among the features.

In [11]:
def create_interactions(interactions_list, buckets=5):
	interactions = []
	for (a, b) in interactions_list:
		interactions.append(tf.feature_column.crossed_column([a, b], hash_bucket_size=buckets))
	return interactions

# Declare the different data types for each column
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']

# Define the feature columns using the above functions
feature_columns = define_feature_column(data, categorical_cols, numeric_cols)
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
derived_feature_columns = create_interactions([['RM', 'LSTAT']])

# Define the model
output_dir = './logs/LinearRegressor_1'
linear_est = tf.estimator.LinearRegressor(
	feature_columns=feature_columns+derived_feature_columns,
	model_dir = output_dir,
	config=tf.estimator.RunConfig().replace(save_summary_steps=100)
)
linear_est.train(train_input_fn)
result = linear_est.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using config: {'_model_dir': './logs/LinearRegressor_1', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py:540: Layer.add_variable (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\keras\optimizer_v2\ftrl.py:144: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./logs/LinearRegressor_1\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 637.4675, step = 0
INFO:tensorflow:global_step/sec: 86.0587
INFO:tensorflow:loss = 63.48009, step = 100 (1.162 sec)
INFO:tensorflow:global_step/sec: 112.994
INFO:tensorflow:loss = 62.024113, step = 200 (0.886 sec)
INFO:tensorflow:global_step/sec: 125.628
INFO:tensorflow:loss = 51.741123, step = 300 (0.796 sec)
INFO:tensorflow:global_step/sec: 126.743
INFO:tensorflow:loss = 48.030235, step = 400 (0.788 sec)
INFO:tensorflow:global_step/sec: 125.471
INFO:tensorflow:loss = 37.587185, step = 500 (0.797 sec)
INFO:tensorflow:global_step/sec: 124.844
INFO:tensorflow:loss = 34.434734, step = 600 (0.801 sec)
INFO:tensorflow:global_step/sec: 125.313
INFO:tensorflow:loss = 40.88792, step = 700 (0.799 sec)
INFO:tensorflow:global_step/sec: 123.153
INFO:tensorflow:loss = 36.25906, step = 800 (0.812 sec)
INFO:tensorflow:global_step/sec: 124.378
INFO:tensorflow:loss = 40.16976, step = 900 (0.803 sec)
INFO:tensorflow:global_step/sec: 125.47
INFO:tensorflow:loss = 35.833035, step = 1000 (0.797 sec)
INFO:tensorflow:global_step/sec: 125.157
INFO:tensorflow:loss = 38.373238, step = 1100 (0.800 sec)
INFO:tensorflow:global_step/sec: 125.47
INFO:tensorflow:loss = 37.9605, step = 1200 (0.796 sec)
INFO:tensorflow:global_step/sec: 123.001
INFO:tensorflow:loss = 37.414146, step = 1300 (0.814 sec)
INFO:tensorflow:global_step/sec: 125.313
INFO:tensorflow:loss = 33.45863, step = 1400 (0.797 sec)
INFO:tensorflow:global_step/sec: 124.224
INFO:tensorflow:loss = 35.344055, step = 1500 (0.805 sec)
INFO:tensorflow:global_step/sec: 125.157
INFO:tensorflow:loss = 32.962963, step = 1600 (0.799 sec)
INFO:tensorflow:global_step/sec: 124.069
INFO:tensorflow:loss = 30.64801, step = 1700 (0.806 sec)
INFO:tensorflow:global_step/sec: 123.61
INFO:tensorflow:loss = 35.50905, step = 1800 (0.810 sec)
INFO:tensorflow:global_step/sec: 122.699
INFO:tensorflow:loss = 36.452656, step = 1900 (0.814 sec)
INFO:tensorflow:global_step/sec: 111.111
INFO:tensorflow:loss = 35.775265, step = 2000 (0.901 sec)
INFO:tensorflow:global_step/sec: 111.111
INFO:tensorflow:loss = 36.627533, step = 2100 (0.899 sec)
INFO:tensorflow:global_step/sec: 109.289
INFO:tensorflow:loss = 30.270222, step = 2200 (0.917 sec)
INFO:tensorflow:global_step/sec: 111.857
INFO:tensorflow:loss = 30.023712, step = 2300 (0.893 sec)
INFO:tensorflow:global_step/sec: 106.496
INFO:tensorflow:loss = 33.271008, step = 2400 (0.938 sec)
INFO:tensorflow:global_step/sec: 100.705
INFO:tensorflow:loss = 27.489845, step = 2500 (0.993 sec)
INFO:tensorflow:global_step/sec: 118.064
INFO:tensorflow:loss = 33.117493, step = 2600 (0.847 sec)
INFO:tensorflow:global_step/sec: 104.602
INFO:tensorflow:loss = 34.200638, step = 2700 (0.956 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 2800...
INFO:tensorflow:Saving checkpoints for 2800 into ./logs/LinearRegressor_1\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 2800...
INFO:tensorflow:Loss for final step: 35.215054.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-14T21:50:46Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/LinearRegressor_1\model.ckpt-2800
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.46770s
INFO:tensorflow:Finished evaluation at 2022-06-14-21:50:47
INFO:tensorflow:Saving dict for global step 2800: average_loss = 31.188597, global_step = 2800, label/mean = 22.048513, loss = 31.188597, prediction/mean = 21.821356
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 2800: ./logs/LinearRegressor_1\model.ckpt-2800
{'average_loss': 31.188597, 'label/mean': 22.048513, 'loss': 31.188597, 'prediction/mean': 21.821356, 'global_step': 2800}

In [16]:
%load_ext tensorboard
%tensorboard --logdir ./logs/LinearRegressor_1

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 15656), started 0:00:55 ago. (Use '!kill 15656' to kill it.)

Fitting is much faster and more stable compared to the previous model => provided more informative features to the model

In [17]:
# For handling predictions
def dicts_to_preds(pred_dicts):
    return np.array([pred['predictions'] for pred in pred_dicts])
preds = dicts_to_preds(linear_est.predict(test_input_fn))
print(preds)

<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/LinearRegressor_1\model.ckpt-2800
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[[25.16673  ]
 [30.87422  ]
 [20.306993 ]
 [22.00883  ]
 [18.296663 ]
 [17.276712 ]
 [18.681643 ]
 [12.968714 ]
 [23.830164 ]
 [25.585846 ]
 [21.270287 ]
 [17.531271 ]
 [29.03054  ]
 [17.33629  ]
 [20.087648 ]
 [21.34022  ]
 [24.42383  ]
 [23.269535 ]
 [24.943975 ]
 [23.070375 ]
 [26.874971 ]
 [25.591692 ]
 [23.303368 ]
 [19.815065 ]
 [21.450205 ]
 [12.169376 ]
 [17.970705 ]
 [21.876566 ]
 [20.764662 ]
 [ 6.3202553]
 [13.513006 ]
 [10.562323 ]
 [20.170954 ]
 [19.552908 ]
 [15.554392 ]
 [33.972084 ]
 [27.86352  ]
 [29.238085 ]
 [34.43915  ]
 [34.338634 ]
 [35.188736 ]
 [16.180632 ]
 [20.545782 ]
 [24.317068 ]
 [36.661472 ]
 [26.522097 ]
 [32.716507 ]
 [24.927473 ]
 [20.667667 ]
 [22.997717 ]
 [27.581203 ]
 [25.176361 ]
 [24.340588 ]
 [30.447317 ]
 [23.876543 ]
 [23.96316  ]
 [33.565914 ]
 [27.907751 ]
 [33.0639   ]
 [27.95528  ]
 [36.24304  ]
 [25.963322 ]
 [16.07948  ]
 [26.846106 ]
 [24.999384 ]
 [15.913498 ]
 [18.612011 ]
 [19.225468 ]
 [23.53012  ]
 [24.620375 ]
 [27.848286 ]
 [23.31684  ]
 [23.680101 ]
 [27.057205 ]
 [13.561449 ]
 [25.17799  ]
 [19.836504 ]
 [ 5.194072 ]
 [ 7.152147 ]
 [21.228605 ]
 [19.112669 ]
 [21.44901  ]
 [20.940727 ]
 [21.083464 ]
 [ 8.468006 ]
 [18.223078 ]
 [12.375423 ]
 [13.078457 ]
 [ 8.844807 ]
 [14.961714 ]
 [20.540623 ]
 [18.642632 ]
 [21.37052  ]
 [18.25163  ]
 [16.7716   ]
 [20.023891 ]
 [22.654032 ]
 [13.661121 ]
 [22.135204 ]
 [14.036909 ]
 [20.000072 ]]

# Turning a Keras model into an Estimator

`tf.estimator` module is good for out-of-the-box models that have flexible deployment options and are scalable, but lack the flexibility in model architecture. Keras instead offers the modularity, which can be combined with Estimators to take advantage of both APIs

Achieve deployability with modularity of models. Reuse the Boston Housing dataset

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()
import tensorflow.keras as keras

In [18]:
# Redefine feature column function to specify input to Keras model
def define_feature_columns_layers(data_df, categorical_cols, numerical_cols):
    feature_columns = []
    feature_layer_inputs = {}
    
    for feature_name in numerical_cols:
        feature_columns.append(tf.feature_column.numeric_column(feature_name, dtype=tf.float32))
        feature_layer_inputs[feature_name] = tf.keras.Input(shape=(1, ), name=feature_name)
    
    for feature_name in categorical_cols:
        vocabulary = data_df[feature_name].unique()
        cat = tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary)
        cat_one_hot = tf.feature_column.indicator_column(cat)
        feature_columns.append(cat_one_hot)
        feature_layer_inputs[feature_name] = tf.keras.Input(shape=(1, ), name=feature_name, dtype=tf.int64)
        # note that the shape for keras.Input is the column, row is automatically None
    
    return feature_columns, feature_layer_inputs 

# Redefine the interaction (combination of 2 variables) feature as well
def create_interactions(interactions_list, buckets=5):
    feature_columns = []

    for (a, b) in interactions_list:
        crossed_features = tf.feature_column.crossed_column([a, b], hash_bucket_size=buckets)
        crossed_features_one_hot = tf.feature_column.indicator_column(crossed_features)
        feature_columns.append(crossed_features_one_hot)
    
    return feature_columns
	
# Define model
def create_linreg(feature_columns, feature_layer_inputs, optimizer):
    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(1, kernel_initializer='normal', activation='linear')(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss='mean_squared_error')
    
    return model

In [8]:
# Create the model 
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']
feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
interaction_columns = create_interactions([['RM', 'LSTAT']])
feature_columns += interaction_columns
optimizer = keras.optimizers.Ftrl(learning_rate=0.02)
model = create_linreg(feature_columns, feature_layer_inputs, optimizer)

In [31]:
# Converting the model into an estimator
import tempfile
def canned_keras(model, output_dir=None):
    if output_dir is None:
        model_dir = tempfile.mkdtemp()
    else:
        model_dir = output_dir
    keras_estimator = tf.keras.estimator.model_to_estimator(
		keras_model=model,
		model_dir=model_dir, 
		config=tf.estimator.RunConfig().replace(save_summary_steps=100)
	)
    return keras_estimator
estimator = canned_keras(model)

# Train the model and evaluate
train_input_fn = make_input_fn(train, y_train, num_epoch=1400)
test_input_fn = make_input_fn(test, y_test, num_epoch=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\MARTIN~1\\AppData\\Local\\Temp\\tmp7vbiwrxj', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

TypeError: make_input_fn() got an unexpected keyword argument 'num_epoch'

Canned Keras Esimators are a quick robust way to combine the flexibility of user-defined models in keras with the high-performance training and deployment of estimators.

# 4c. Understanding Loss Functions in Linear Regression

Goal: Understand the effect of loss function in algorithm convergence.

Illustrate how the L1 and L2 loss functions affect convergence and predictions in linear regression. Continue to use the Boston Housing dataset.

In [32]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

In [33]:
# Redefine create_linreg by adding new parameter to control the loss function
def create_linreg(feature_columns, feature_layer_inputs, optimizer, loss='mean_squared_error', metrics=['mean_absolute_error']):
    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(1, kernel_initializer='normal', activation='linear')(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    return model

In [34]:
# Defining the columns
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']
feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
interactions_columns = create_interactions([['RM', 'LSTAT']])

feature_columns += interactions_columns

optimizer = keras.optimizers.Ftrl(learning_rate=0.02)

# Create the model with L1 loss instead
model = create_linreg(
    feature_columns, 
    feature_layer_inputs, 
    optimizer, 
    loss='mean_absolute_error', 
    metrics=['mean_absolute_error', 'mean_squared_error']
)
estimator = canned_keras(model, output_dir='logs/L1_Loss')
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using config: {'_model_dir': 'logs/L1_Loss', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='logs/L1_Loss\\keras\\keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: logs/L1_Loss\keras\keras_model.ckpt
INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.
INFO:tensorflow:Warm-started 4 variables.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into logs/L1_Loss\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 22.127344, step = 0
INFO:tensorflow:global_step/sec: 161.03
INFO:tensorflow:loss = 21.217258, step = 100 (0.622 sec)
INFO:tensorflow:global_step/sec: 199.204
INFO:tensorflow:loss = 13.753646, step = 200 (0.502 sec)
INFO:tensorflow:global_step/sec: 183.488
INFO:tensorflow:loss = 7.3466697, step = 300 (0.544 sec)
INFO:tensorflow:global_step/sec: 160
INFO:tensorflow:loss = 4.8869085, step = 400 (0.626 sec)
INFO:tensorflow:global_step/sec: 190.114
INFO:tensorflow:loss = 4.6685176, step = 500 (0.525 sec)
INFO:tensorflow:global_step/sec: 194.175
INFO:tensorflow:loss = 4.104058, step = 600 (0.516 sec)
INFO:tensorflow:global_step/sec: 191.204
INFO:tensorflow:loss = 3.9235384, step = 700 (0.523 sec)
INFO:tensorflow:global_step/sec: 196.08
INFO:tensorflow:loss = 4.227934, step = 800 (0.510 sec)
INFO:tensorflow:global_step/sec: 192.677
INFO:tensorflow:loss = 4.0627356, step = 900 (0.519 sec)
INFO:tensorflow:global_step/sec: 211.864
INFO:tensorflow:loss = 3.8038936, step = 1000 (0.471 sec)
INFO:tensorflow:global_step/sec: 236.408
INFO:tensorflow:loss = 3.591845, step = 1100 (0.423 sec)
INFO:tensorflow:global_step/sec: 248.756
INFO:tensorflow:loss = 3.3556442, step = 1200 (0.403 sec)
INFO:tensorflow:global_step/sec: 242.13
INFO:tensorflow:loss = 3.5046566, step = 1300 (0.413 sec)
INFO:tensorflow:global_step/sec: 252.917
INFO:tensorflow:loss = 3.3361268, step = 1400 (0.395 sec)
INFO:tensorflow:global_step/sec: 258.184
INFO:tensorflow:loss = 3.306882, step = 1500 (0.387 sec)
INFO:tensorflow:global_step/sec: 250.556
INFO:tensorflow:loss = 3.1808834, step = 1600 (0.398 sec)
INFO:tensorflow:global_step/sec: 255.516
INFO:tensorflow:loss = 3.23951, step = 1700 (0.392 sec)
INFO:tensorflow:global_step/sec: 251.882
INFO:tensorflow:loss = 3.2254665, step = 1800 (0.396 sec)
INFO:tensorflow:global_step/sec: 257.056
INFO:tensorflow:loss = 3.1926072, step = 1900 (0.389 sec)
INFO:tensorflow:global_step/sec: 252.094
INFO:tensorflow:loss = 3.2344954, step = 2000 (0.397 sec)
INFO:tensorflow:global_step/sec: 232.346
INFO:tensorflow:loss = 3.265553, step = 2100 (0.430 sec)
INFO:tensorflow:global_step/sec: 223.214
INFO:tensorflow:loss = 3.1077213, step = 2200 (0.448 sec)
INFO:tensorflow:global_step/sec: 224.718
INFO:tensorflow:loss = 3.1815498, step = 2300 (0.445 sec)
INFO:tensorflow:global_step/sec: 218.82
INFO:tensorflow:loss = 3.2522583, step = 2400 (0.458 sec)
INFO:tensorflow:global_step/sec: 202.839
INFO:tensorflow:loss = 2.9886918, step = 2500 (0.492 sec)
INFO:tensorflow:global_step/sec: 225.735
INFO:tensorflow:loss = 3.315608, step = 2600 (0.444 sec)
INFO:tensorflow:global_step/sec: 228.31
INFO:tensorflow:loss = 2.81816, step = 2700 (0.437 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 2800...
INFO:tensorflow:Saving checkpoints for 2800 into logs/L1_Loss\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 2800...
INFO:tensorflow:Loss for final step: 3.631704.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-21T22:07:29Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/L1_Loss\model.ckpt-2800
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.22796s
INFO:tensorflow:Finished evaluation at 2022-06-21-22:07:29
INFO:tensorflow:Saving dict for global step 2800: global_step = 2800, loss = 3.1188207, mean_absolute_error = 3.1188207, mean_squared_error = 27.168404
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 2800: logs/L1_Loss\model.ckpt-2800
{'loss': 3.1188207, 'mean_absolute_error': 3.1188207, 'mean_squared_error': 27.168404, 'global_step': 2800}

In [38]:
%load_ext tensorboard
%tensorboard --logdir ./logs/L1_Loss

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

## On Learning Rates

Too small a learning rate and the convergence will be slow, too large a learning rate and the algorithm might overshoot the minima. Furthermore, different algorithms have different "reactions" to different learning rates. 

For e.g L2 norms are more sensitive to large learning rates due to the design of the loss function as compared to L1 norms

Therefore it's important to select the learning rate based on algorithm, scenario and step

# 4d. Implementing Lasso and Ridge Regression

Regularization methods are used to limit the influence of the coefficients on the regression output. The regularization term is added to the back of the loss function to limit the slopes in the algorithm. 

This limits the number/impact of features have on the impact of dependent features

$$
L_{lasso}(\hat{\beta}) = \sum_{i=1}^{n}(y_i-x'_i\hat{\beta})^2+\lambda \sum_{j=1}^{m}|\hat{\beta}_j| \\
L_{ridge}(\hat{\beta}) = \sum_{i=1}^{n}(y_i-x'_i\hat{\beta})^2+\lambda \sum_{j=1}^{m}w_j\hat{\beta}_j^2 \\
$$

In [59]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

def create_ridge_linreg(feature_columns, feature_layer_inputs, optimizer, loss='mean_squared_error', metrics=['mean_absolute_error'], l2=0.01):
    regularizer = keras.regularizers.l2(l2)
    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(
		1,
		kernel_initializer='normal',
		kernel_regularizer=regularizer,
		activation='linear'
	)(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    return model

In [60]:
# Defining the columns
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']
feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
interactions_columns = create_interactions([['RM', 'LSTAT']])

feature_columns += interactions_columns

optimizer = keras.optimizers.Ftrl(learning_rate=0.02)

# Create model with L2 (ridge regression) and L2 norm
model = create_ridge_linreg(
    feature_columns, 
    feature_layer_inputs, 
    optimizer, 
    loss='mean_squared_error', 
    metrics=['mean_absolute_error', 'mean_squared_error'],
    l2=0.01
)
estimator = canned_keras(model, output_dir='logs/Ridge')
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using config: {'_model_dir': 'logs/Ridge', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/Ridge\model.ckpt-5600
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5600...
INFO:tensorflow:Saving checkpoints for 5600 into logs/Ridge\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5600...
INFO:tensorflow:loss = 22.151453, step = 5600
INFO:tensorflow:global_step/sec: 99.5395
INFO:tensorflow:loss = 19.566742, step = 5700 (1.011 sec)
INFO:tensorflow:global_step/sec: 111.062
INFO:tensorflow:loss = 22.677864, step = 5800 (0.899 sec)
INFO:tensorflow:global_step/sec: 109.83
INFO:tensorflow:loss = 21.879246, step = 5900 (0.907 sec)
INFO:tensorflow:global_step/sec: 132.292
INFO:tensorflow:loss = 21.93441, step = 6000 (0.756 sec)
INFO:tensorflow:global_step/sec: 130.465
INFO:tensorflow:loss = 22.440321, step = 6100 (0.766 sec)
INFO:tensorflow:global_step/sec: 132.226
INFO:tensorflow:loss = 22.07722, step = 6200 (0.757 sec)
INFO:tensorflow:global_step/sec: 130.597
INFO:tensorflow:loss = 18.1954, step = 6300 (0.770 sec)
INFO:tensorflow:global_step/sec: 119.602
INFO:tensorflow:loss = 25.373365, step = 6400 (0.833 sec)
INFO:tensorflow:global_step/sec: 102.359
INFO:tensorflow:loss = 21.283915, step = 6500 (0.981 sec)
INFO:tensorflow:global_step/sec: 116.568
INFO:tensorflow:loss = 19.268806, step = 6600 (0.854 sec)
INFO:tensorflow:global_step/sec: 128.896
INFO:tensorflow:loss = 24.912241, step = 6700 (0.775 sec)
INFO:tensorflow:global_step/sec: 131.733
INFO:tensorflow:loss = 25.763748, step = 6800 (0.762 sec)
INFO:tensorflow:global_step/sec: 122.607
INFO:tensorflow:loss = 21.752304, step = 6900 (0.814 sec)
INFO:tensorflow:global_step/sec: 124.231
INFO:tensorflow:loss = 20.540365, step = 7000 (0.804 sec)
INFO:tensorflow:global_step/sec: 131.414
INFO:tensorflow:loss = 23.731295, step = 7100 (0.761 sec)
INFO:tensorflow:global_step/sec: 98.5759
INFO:tensorflow:loss = 23.5334, step = 7200 (1.015 sec)
INFO:tensorflow:global_step/sec: 111.345
INFO:tensorflow:loss = 24.08143, step = 7300 (0.902 sec)
INFO:tensorflow:global_step/sec: 123.412
INFO:tensorflow:loss = 20.096727, step = 7400 (0.807 sec)
INFO:tensorflow:global_step/sec: 107.936
INFO:tensorflow:loss = 18.473852, step = 7500 (0.926 sec)
INFO:tensorflow:global_step/sec: 97.2464
INFO:tensorflow:loss = 22.539047, step = 7600 (1.028 sec)
INFO:tensorflow:global_step/sec: 118.784
INFO:tensorflow:loss = 19.898148, step = 7700 (0.842 sec)
INFO:tensorflow:global_step/sec: 124.283
INFO:tensorflow:loss = 21.714663, step = 7800 (0.805 sec)
INFO:tensorflow:global_step/sec: 128.141
INFO:tensorflow:loss = 21.422266, step = 7900 (0.780 sec)
INFO:tensorflow:global_step/sec: 126.951
INFO:tensorflow:loss = 22.830679, step = 8000 (0.788 sec)
INFO:tensorflow:global_step/sec: 130.647
INFO:tensorflow:loss = 16.627054, step = 8100 (0.765 sec)
INFO:tensorflow:global_step/sec: 114.779
INFO:tensorflow:loss = 18.147158, step = 8200 (0.871 sec)
INFO:tensorflow:global_step/sec: 124.023
INFO:tensorflow:loss = 24.046669, step = 8300 (0.806 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 8400...
INFO:tensorflow:Saving checkpoints for 8400 into logs/Ridge\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 8400...
INFO:tensorflow:Loss for final step: 18.430094.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-21T23:04:55Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/Ridge\model.ckpt-8400
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.33502s
INFO:tensorflow:Finished evaluation at 2022-06-21-23:04:56
INFO:tensorflow:Saving dict for global step 8400: global_step = 8400, loss = 23.406042, mean_absolute_error = 3.1470401, mean_squared_error = 23.167526
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 8400: logs/Ridge\model.ckpt-8400
{'loss': 23.406042, 'mean_absolute_error': 3.1470401, 'mean_squared_error': 23.167526, 'global_step': 8400}

In [66]:
# Lasso Regularization
def create_lasso_linreg(feature_columns, feature_layer_inputs, optimizer, loss='mean_squared_error', metrics=['mean_absolute_error'], l1=0.001):
    regularizer = keras.regularizers.l1(l1)
    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(
		1,
		kernel_initializer='normal',
		kernel_regularizer=regularizer,
		activation='linear'
	)(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    return model

In [67]:
# Defining the columns
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']
feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
interactions_columns = create_interactions([['RM', 'LSTAT']])

feature_columns += interactions_columns

optimizer = keras.optimizers.Ftrl(learning_rate=0.02)

# Create model with L1 (lasso) and L2 norm
model = create_lasso_linreg(
    feature_columns, 
    feature_layer_inputs, 
    optimizer, 
    loss='mean_squared_error', 
    metrics=['mean_absolute_error', 'mean_squared_error'],
    l1=0.001
)
estimator = canned_keras(model, output_dir='logs/Lasso')
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using config: {'_model_dir': 'logs/Lasso', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/Lasso\model.ckpt-5600
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5600...
INFO:tensorflow:Saving checkpoints for 5600 into logs/Lasso\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5600...
INFO:tensorflow:loss = 23.710516, step = 5600
INFO:tensorflow:global_step/sec: 187.683
INFO:tensorflow:loss = 24.061947, step = 5700 (0.534 sec)
INFO:tensorflow:global_step/sec: 221.73
INFO:tensorflow:loss = 21.531916, step = 5800 (0.450 sec)
INFO:tensorflow:global_step/sec: 234.743
INFO:tensorflow:loss = 25.109652, step = 5900 (0.426 sec)
INFO:tensorflow:global_step/sec: 241.547
INFO:tensorflow:loss = 20.38251, step = 6000 (0.414 sec)
INFO:tensorflow:global_step/sec: 245.098
INFO:tensorflow:loss = 20.16513, step = 6100 (0.408 sec)
INFO:tensorflow:global_step/sec: 250.625
INFO:tensorflow:loss = 21.646252, step = 6200 (0.399 sec)
INFO:tensorflow:global_step/sec: 226.244
INFO:tensorflow:loss = 22.310038, step = 6300 (0.443 sec)
INFO:tensorflow:global_step/sec: 233.646
INFO:tensorflow:loss = 24.397469, step = 6400 (0.428 sec)
INFO:tensorflow:global_step/sec: 225.734
INFO:tensorflow:loss = 22.220058, step = 6500 (0.442 sec)
INFO:tensorflow:global_step/sec: 252.524
INFO:tensorflow:loss = 25.153397, step = 6600 (0.396 sec)
INFO:tensorflow:global_step/sec: 254.454
INFO:tensorflow:loss = 20.389137, step = 6700 (0.393 sec)
INFO:tensorflow:global_step/sec: 247.524
INFO:tensorflow:loss = 17.965572, step = 6800 (0.404 sec)
INFO:tensorflow:global_step/sec: 239.808
INFO:tensorflow:loss = 23.851696, step = 6900 (0.417 sec)
INFO:tensorflow:global_step/sec: 243.308
INFO:tensorflow:loss = 22.891691, step = 7000 (0.411 sec)
INFO:tensorflow:global_step/sec: 253.809
INFO:tensorflow:loss = 21.615816, step = 7100 (0.394 sec)
INFO:tensorflow:global_step/sec: 248.138
INFO:tensorflow:loss = 22.978199, step = 7200 (0.403 sec)
INFO:tensorflow:global_step/sec: 246.914
INFO:tensorflow:loss = 22.73453, step = 7300 (0.405 sec)
INFO:tensorflow:global_step/sec: 247.524
INFO:tensorflow:loss = 19.75812, step = 7400 (0.405 sec)
INFO:tensorflow:global_step/sec: 245.74
INFO:tensorflow:loss = 20.7235, step = 7500 (0.406 sec)
INFO:tensorflow:global_step/sec: 250.577
INFO:tensorflow:loss = 23.479553, step = 7600 (0.399 sec)
INFO:tensorflow:global_step/sec: 247.556
INFO:tensorflow:loss = 19.024513, step = 7700 (0.405 sec)
INFO:tensorflow:global_step/sec: 217.994
INFO:tensorflow:loss = 16.863533, step = 7800 (0.458 sec)
INFO:tensorflow:global_step/sec: 222.221
INFO:tensorflow:loss = 22.715878, step = 7900 (0.451 sec)
INFO:tensorflow:global_step/sec: 234.182
INFO:tensorflow:loss = 20.75052, step = 8000 (0.427 sec)
INFO:tensorflow:global_step/sec: 251.27
INFO:tensorflow:loss = 21.513533, step = 8100 (0.397 sec)
INFO:tensorflow:global_step/sec: 239.218
INFO:tensorflow:loss = 22.422995, step = 8200 (0.418 sec)
INFO:tensorflow:global_step/sec: 251.975
INFO:tensorflow:loss = 23.5443, step = 8300 (0.397 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 8400...
INFO:tensorflow:Saving checkpoints for 8400 into logs/Lasso\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 8400...
INFO:tensorflow:Loss for final step: 22.511776.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-21T23:32:42Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/Lasso\model.ckpt-8400
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.19483s
INFO:tensorflow:Finished evaluation at 2022-06-21-23:32:42
INFO:tensorflow:Saving dict for global step 8400: global_step = 8400, loss = 23.035013, mean_absolute_error = 3.1332355, mean_squared_error = 23.010035
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 8400: logs/Lasso\model.ckpt-8400
{'loss': 23.035013, 'mean_absolute_error': 3.1332355, 'mean_squared_error': 23.010035, 'global_step': 8400}

__Result__

Test results favour Lasso. Could be explained by a noisy variable that had to be exlcuded in order for the model to improve.

By comparing how the Lasso and Ridge Regression algorithms are structured, Lasso will force coefficients to zero, while Ridge Regression will only decrease coefficients close to zero (but never zero), therefore some less useful features will still have an effect on the model causing the results to be slightly different between the 2 regularization methods.

## Extention - Elastic net regression

Elastic net regression is a type of regularization that combines both Lasso and Ridge Regression by adding L1 and L2 regularization terms to the loss function.

$$
L_{elasticNet}(\hat{\beta}) = \sum_{i=1}^{n}(y_i-x'_i\hat{\beta})^2+r\lambda\sum_{j=1}^{m}|\hat{\beta}_j| + \frac{1-r}{2}\lambda \sum_{j=1}^{m}w_j\hat{\beta}_j^2
$$

In [68]:
# ElasticNet Regularization
def create_elasticnet_linreg(feature_columns, feature_layer_inputs, optimizer, loss='mean_squared_error', metrics=['mean_absolute_error'], l1=0.001, l2=0.01):
    regularizer = keras.regularizers.l1_l2(l1, l2)
    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(
		1,
		kernel_initializer='normal',
		kernel_regularizer=regularizer,
		activation='linear'
	)(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    return model

In [69]:
# Defining the columns
categorical_cols = ['CHAS', 'RAD']
numeric_cols = ['CRIM', 'ZN', 'INDUS',  'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']
feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
interactions_columns = create_interactions([['RM', 'LSTAT']])

feature_columns += interactions_columns

optimizer = keras.optimizers.Ftrl(learning_rate=0.02)

# Create model with ElasticNet (l1 + l2 regularization) with L2 norm
model = create_elasticnet_linreg(
    feature_columns, 
    feature_layer_inputs, 
    optimizer, 
    loss='mean_squared_error', 
    metrics=['mean_absolute_error', 'mean_squared_error'],
    l1=0.001,
    l2=0.01
)
estimator = canned_keras(model, output_dir='logs/ElasticNet')
train_input_fn = make_input_fn(train, y_train, num_epochs=1400)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
INFO:tensorflow:Using config: {'_model_dir': 'logs/ElasticNet', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='logs/ElasticNet\\keras\\keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: logs/ElasticNet\keras\keras_model.ckpt
INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.
INFO:tensorflow:Warm-started 4 variables.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into logs/ElasticNet\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 569.224, step = 0
INFO:tensorflow:global_step/sec: 154.32
INFO:tensorflow:loss = 288.59372, step = 100 (0.649 sec)
INFO:tensorflow:global_step/sec: 181.159
INFO:tensorflow:loss = 136.68835, step = 200 (0.554 sec)
INFO:tensorflow:global_step/sec: 130.719
INFO:tensorflow:loss = 71.54406, step = 300 (0.764 sec)
INFO:tensorflow:global_step/sec: 158.983
INFO:tensorflow:loss = 44.88981, step = 400 (0.629 sec)
INFO:tensorflow:global_step/sec: 152.438
INFO:tensorflow:loss = 38.80285, step = 500 (0.656 sec)
INFO:tensorflow:global_step/sec: 169.492
INFO:tensorflow:loss = 35.9657, step = 600 (0.591 sec)
INFO:tensorflow:global_step/sec: 192.306
INFO:tensorflow:loss = 37.496513, step = 700 (0.520 sec)
INFO:tensorflow:global_step/sec: 170.07
INFO:tensorflow:loss = 34.758137, step = 800 (0.587 sec)
INFO:tensorflow:global_step/sec: 163.398
INFO:tensorflow:loss = 26.461548, step = 900 (0.612 sec)
INFO:tensorflow:global_step/sec: 163.666
INFO:tensorflow:loss = 29.60857, step = 1000 (0.611 sec)
INFO:tensorflow:global_step/sec: 166.945
INFO:tensorflow:loss = 31.573023, step = 1100 (0.599 sec)
INFO:tensorflow:global_step/sec: 203.253
INFO:tensorflow:loss = 28.06513, step = 1200 (0.491 sec)
INFO:tensorflow:global_step/sec: 232.018
INFO:tensorflow:loss = 25.95675, step = 1300 (0.431 sec)
INFO:tensorflow:global_step/sec: 235.295
INFO:tensorflow:loss = 27.633131, step = 1400 (0.425 sec)
INFO:tensorflow:global_step/sec: 247.524
INFO:tensorflow:loss = 23.835089, step = 1500 (0.405 sec)
INFO:tensorflow:global_step/sec: 242.719
INFO:tensorflow:loss = 27.188173, step = 1600 (0.412 sec)
INFO:tensorflow:global_step/sec: 245.7
INFO:tensorflow:loss = 25.74327, step = 1700 (0.406 sec)
INFO:tensorflow:global_step/sec: 248.757
INFO:tensorflow:loss = 22.69292, step = 1800 (0.402 sec)
INFO:tensorflow:global_step/sec: 249.999
INFO:tensorflow:loss = 26.157553, step = 1900 (0.401 sec)
INFO:tensorflow:global_step/sec: 244.498
INFO:tensorflow:loss = 26.600864, step = 2000 (0.409 sec)
INFO:tensorflow:global_step/sec: 236.393
INFO:tensorflow:loss = 23.911463, step = 2100 (0.422 sec)
INFO:tensorflow:global_step/sec: 251.272
INFO:tensorflow:loss = 24.848587, step = 2200 (0.398 sec)
INFO:tensorflow:global_step/sec: 251.888
INFO:tensorflow:loss = 26.08711, step = 2300 (0.397 sec)
INFO:tensorflow:global_step/sec: 246.307
INFO:tensorflow:loss = 23.361486, step = 2400 (0.407 sec)
INFO:tensorflow:global_step/sec: 249.376
INFO:tensorflow:loss = 27.820105, step = 2500 (0.401 sec)
INFO:tensorflow:global_step/sec: 244.499
INFO:tensorflow:loss = 20.276924, step = 2600 (0.408 sec)
INFO:tensorflow:global_step/sec: 228.311
INFO:tensorflow:loss = 23.559116, step = 2700 (0.439 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 2800...
INFO:tensorflow:Saving checkpoints for 2800 into logs/ElasticNet\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 2800...
INFO:tensorflow:Loss for final step: 18.816286.
<RepeatDataset shapes: ({CRIM: (None,), ZN: (None,), INDUS: (None,), CHAS: (None,), NOX: (None,), RM: (None,), AGE: (None,), DIS: (None,), RAD: (None,), TAX: (None,), PTRATIO: (None,), B: (None,), LSTAT: (None,)}, (None,)), types: ({CRIM: tf.float64, ZN: tf.float64, INDUS: tf.float64, CHAS: tf.int64, NOX: tf.float64, RM: tf.float64, AGE: tf.float64, DIS: tf.float64, RAD: tf.int64, TAX: tf.float64, PTRATIO: tf.float64, B: tf.float64, LSTAT: tf.float64}, tf.float64)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-21T23:33:14Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from logs/ElasticNet\model.ckpt-2800
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.23599s
INFO:tensorflow:Finished evaluation at 2022-06-21-23:33:14
INFO:tensorflow:Saving dict for global step 2800: global_step = 2800, loss = 25.188786, mean_absolute_error = 3.2364035, mean_squared_error = 24.936169
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 2800: logs/ElasticNet\model.ckpt-2800
{'loss': 25.188786, 'mean_absolute_error': 3.2364035, 'mean_squared_error': 24.936169, 'global_step': 2800}

__Result__

Model doesn't outperform Lasso, since this problem involves redundant variable in the prediction, therefore, Lasso is still the better choice

# 4e. Implementing Logisitic Regression
Turn linear regression in to a binary classification problem. By applying the sigmoid function to the linear output, it scales the result from zero to one, representing the probability that the data point exists in one class or not. 

## Selecting the Cutoff
By then specified a cutoff of __0.5__, the model can determine which class the outcome belongs to. This value can however be tuned according to the obejctive of the model. 

E.g By increasing the threshold, we reduce the number of class 1 predictions, meaning that the number of false negatives increase. However this would mean that those thare are predicted to be in class 1 will have high likelihood to be in class 1, which those more in between will be classified as 0. This means the model is highly precise at the cost of missing out some potential positive cases.

On the flipside, if the use case for the model was to be used to detect cancer having a higher false positive rate compared to a false negative rate is always better, therefore the threshold of determining a class 1 case might be lower.

A 0.5 threshold means that the model is balanced between false positives and false negativse. The final threshold is always somethign that has to be considered depending on the model's real-world applications

## About the Dataset
Logistic regression to preduict the probability of breast cancer using the Breast Cancer Wisconsin dataset. Predicting the diagnosis from features  that are computed from a digitized image of a __fine needle aspiration (FNA)__.

Dataset can immediately be used as a classification model without further transformations

In [39]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

# Data preparation
breast_cancer = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
path = tf.keras.utils.get_file(breast_cancer.split('/')[-1], breast_cancer)

columns = ['sample_code', 'clump_thickness', 'cell_size_uniformity', 'cell_shape_uniformity',
           'marginal_adhesion', 'single_epithelial_cell_size', 'bare_nuclei', 'bland_chromatin',
           'normal_nucleoli', 'mitoses', 'class']

data = pd.read_csv(path, header=None, names=columns, na_values=[np.nan, '?'])
# Code to see which rows has null values
# data[data.isnull().any(axis=1)]
data = data.fillna(data.median()) # fill the NA values with the median value of the column

# Splitting the data
np.random.seed(1)
train = data.sample(frac=0.8).copy()
y_train = (train['class'] == 4).astype(int)
train.drop(['sample_code', 'class'], axis=1, inplace=True)

test = data.loc[~data.index.isin(train.index)].copy()
y_test = (test['class'] == 4).astype(int)
test.drop(['sample_code', 'class'], axis=1, inplace=True)

print(f"Distribution of samples: Training samples - {train.shape[0]} | Testing samples - {test.shape[0]}")

Distribution of samples: Training samples - 559 | Testing samples - 140

In [33]:
# Model deifnition - Change the activation function in the single output neuron from 'linear' to 'sigmoid'
def create_logreg(feature_columns, feature_layer_inputs, optimizer, loss='binary_crossentropy', metrics=['accuracy'], l2=0.01):
    regularizer = keras.regularizers.l2(l2)

    feature_layer = keras.layers.DenseFeatures(feature_columns)
    feature_layer_outputs = feature_layer(feature_layer_inputs)
    norm = keras.layers.BatchNormalization()(feature_layer_outputs)
    outputs = keras.layers.Dense(1, 
                                 kernel_initializer='normal', 
                                 kernel_regularizer = regularizer, 
                                 activation='sigmoid')(norm)
    
    model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    return model

In [34]:
# Run the model
categorical_cols = []
numeric_cols = ['clump_thickness', 'cell_size_uniformity', 'cell_shape_uniformity',
                'marginal_adhesion', 'single_epithelial_cell_size', 'bare_nuclei', 'bland_chromatin',
                'normal_nucleoli', 'mitoses']

feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
optimizer = keras.optimizers.Ftrl(learning_rate=0.007)
model = create_logreg(feature_columns, feature_layer_inputs, optimizer, l2=0.01)
estimator = canned_keras(model, output_dir='./logs/logreg')

train_input_fn = make_input_fn(train, y_train, num_epochs=300, batch_size=32)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\keras\optimizer_v2\ftrl.py:144: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Using config: {'_model_dir': './logs/logreg', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
<RepeatDataset shapes: ({clump_thickness: (None,), cell_size_uniformity: (None,), cell_shape_uniformity: (None,), marginal_adhesion: (None,), single_epithelial_cell_size: (None,), bare_nuclei: (None,), bland_chromatin: (None,), normal_nucleoli: (None,), mitoses: (None,)}, (None,)), types: ({clump_thickness: tf.int64, cell_size_uniformity: tf.int64, cell_shape_uniformity: tf.int64, marginal_adhesion: tf.int64, single_epithelial_cell_size: tf.int64, bare_nuclei: tf.float64, bland_chromatin: tf.int64, normal_nucleoli: tf.int64, mitoses: tf.int64}, tf.int32)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='./logs/logreg\\keras\\keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: ./logs/logreg\keras\keras_model.ckpt
INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.
INFO:tensorflow:Warm-started 4 variables.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./logs/logreg\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.7449155, step = 0
INFO:tensorflow:global_step/sec: 304.113
INFO:tensorflow:loss = 0.674561, step = 100 (0.328 sec)
INFO:tensorflow:global_step/sec: 437.675
INFO:tensorflow:loss = 0.67718434, step = 200 (0.228 sec)
INFO:tensorflow:global_step/sec: 432.122
INFO:tensorflow:loss = 0.6437294, step = 300 (0.232 sec)
INFO:tensorflow:global_step/sec: 448.297
INFO:tensorflow:loss = 0.6152078, step = 400 (0.223 sec)
INFO:tensorflow:global_step/sec: 436.682
INFO:tensorflow:loss = 0.65935, step = 500 (0.228 sec)
INFO:tensorflow:global_step/sec: 423.727
INFO:tensorflow:loss = 0.54058087, step = 600 (0.236 sec)
INFO:tensorflow:global_step/sec: 450.448
INFO:tensorflow:loss = 0.50842583, step = 700 (0.222 sec)
INFO:tensorflow:global_step/sec: 438.596
INFO:tensorflow:loss = 0.43462822, step = 800 (0.229 sec)
INFO:tensorflow:global_step/sec: 456.626
INFO:tensorflow:loss = 0.48085606, step = 900 (0.219 sec)
INFO:tensorflow:global_step/sec: 450.449
INFO:tensorflow:loss = 0.4230482, step = 1000 (0.221 sec)
INFO:tensorflow:global_step/sec: 456.619
INFO:tensorflow:loss = 0.3630583, step = 1100 (0.219 sec)
INFO:tensorflow:global_step/sec: 446.431
INFO:tensorflow:loss = 0.35049915, step = 1200 (0.224 sec)
INFO:tensorflow:global_step/sec: 444.442
INFO:tensorflow:loss = 0.31040943, step = 1300 (0.225 sec)
INFO:tensorflow:global_step/sec: 448.428
INFO:tensorflow:loss = 0.40723267, step = 1400 (0.224 sec)
INFO:tensorflow:global_step/sec: 429.187
INFO:tensorflow:loss = 0.3421515, step = 1500 (0.232 sec)
INFO:tensorflow:global_step/sec: 444.446
INFO:tensorflow:loss = 0.20703469, step = 1600 (0.225 sec)
INFO:tensorflow:global_step/sec: 442.48
INFO:tensorflow:loss = 0.24367563, step = 1700 (0.226 sec)
INFO:tensorflow:global_step/sec: 444.444
INFO:tensorflow:loss = 0.3507575, step = 1800 (0.225 sec)
INFO:tensorflow:global_step/sec: 456.622
INFO:tensorflow:loss = 0.19247465, step = 1900 (0.219 sec)
INFO:tensorflow:global_step/sec: 460.828
INFO:tensorflow:loss = 0.19246148, step = 2000 (0.218 sec)
INFO:tensorflow:global_step/sec: 429.183
INFO:tensorflow:loss = 0.1957165, step = 2100 (0.232 sec)
INFO:tensorflow:global_step/sec: 396.827
INFO:tensorflow:loss = 0.2874693, step = 2200 (0.253 sec)
INFO:tensorflow:global_step/sec: 452.488
INFO:tensorflow:loss = 0.20201813, step = 2300 (0.220 sec)
INFO:tensorflow:global_step/sec: 444.444
INFO:tensorflow:loss = 0.16630316, step = 2400 (0.225 sec)
INFO:tensorflow:global_step/sec: 440.529
INFO:tensorflow:loss = 0.16356638, step = 2500 (0.227 sec)
INFO:tensorflow:global_step/sec: 448.43
INFO:tensorflow:loss = 0.15871508, step = 2600 (0.223 sec)
INFO:tensorflow:global_step/sec: 460.83
INFO:tensorflow:loss = 0.13159785, step = 2700 (0.217 sec)
INFO:tensorflow:global_step/sec: 434.783
INFO:tensorflow:loss = 0.2067829, step = 2800 (0.231 sec)
INFO:tensorflow:global_step/sec: 454.546
INFO:tensorflow:loss = 0.13337356, step = 2900 (0.220 sec)
INFO:tensorflow:global_step/sec: 442.474
INFO:tensorflow:loss = 0.14665602, step = 3000 (0.226 sec)
INFO:tensorflow:global_step/sec: 440.53
INFO:tensorflow:loss = 0.1885491, step = 3100 (0.226 sec)
INFO:tensorflow:global_step/sec: 429.133
INFO:tensorflow:loss = 0.2058037, step = 3200 (0.233 sec)
INFO:tensorflow:global_step/sec: 431.088
INFO:tensorflow:loss = 0.12546834, step = 3300 (0.232 sec)
INFO:tensorflow:global_step/sec: 436.624
INFO:tensorflow:loss = 0.21042347, step = 3400 (0.229 sec)
INFO:tensorflow:global_step/sec: 456.68
INFO:tensorflow:loss = 0.18513688, step = 3500 (0.219 sec)
INFO:tensorflow:global_step/sec: 444.445
INFO:tensorflow:loss = 0.16625838, step = 3600 (0.225 sec)
INFO:tensorflow:global_step/sec: 431.032
INFO:tensorflow:loss = 0.12582345, step = 3700 (0.232 sec)
INFO:tensorflow:global_step/sec: 432.85
INFO:tensorflow:loss = 0.13044003, step = 3800 (0.231 sec)
INFO:tensorflow:global_step/sec: 446.487
INFO:tensorflow:loss = 0.11068486, step = 3900 (0.224 sec)
INFO:tensorflow:global_step/sec: 442.477
INFO:tensorflow:loss = 0.21177047, step = 4000 (0.226 sec)
INFO:tensorflow:global_step/sec: 446.42
INFO:tensorflow:loss = 0.15128043, step = 4100 (0.225 sec)
INFO:tensorflow:global_step/sec: 438.592
INFO:tensorflow:loss = 0.242807, step = 4200 (0.228 sec)
INFO:tensorflow:global_step/sec: 416.677
INFO:tensorflow:loss = 0.1426882, step = 4300 (0.239 sec)
INFO:tensorflow:global_step/sec: 429.184
INFO:tensorflow:loss = 0.1292036, step = 4400 (0.233 sec)
INFO:tensorflow:global_step/sec: 431.034
INFO:tensorflow:loss = 0.1504329, step = 4500 (0.233 sec)
INFO:tensorflow:global_step/sec: 442.48
INFO:tensorflow:loss = 0.10298744, step = 4600 (0.226 sec)
INFO:tensorflow:global_step/sec: 423.731
INFO:tensorflow:loss = 0.12238968, step = 4700 (0.235 sec)
INFO:tensorflow:global_step/sec: 438.589
INFO:tensorflow:loss = 0.20394008, step = 4800 (0.228 sec)
INFO:tensorflow:global_step/sec: 425.538
INFO:tensorflow:loss = 0.17531843, step = 4900 (0.235 sec)
INFO:tensorflow:global_step/sec: 452.489
INFO:tensorflow:loss = 0.14150514, step = 5000 (0.222 sec)
INFO:tensorflow:global_step/sec: 421.944
INFO:tensorflow:loss = 0.1341911, step = 5100 (0.236 sec)
INFO:tensorflow:global_step/sec: 438.593
INFO:tensorflow:loss = 0.12242086, step = 5200 (0.228 sec)
INFO:tensorflow:global_step/sec: 427.349
INFO:tensorflow:loss = 0.14065441, step = 5300 (0.234 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5400...
INFO:tensorflow:Saving checkpoints for 5400 into ./logs/logreg\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5400...
INFO:tensorflow:Loss for final step: 0.24521844.
<RepeatDataset shapes: ({clump_thickness: (None,), cell_size_uniformity: (None,), cell_shape_uniformity: (None,), marginal_adhesion: (None,), single_epithelial_cell_size: (None,), bare_nuclei: (None,), bland_chromatin: (None,), normal_nucleoli: (None,), mitoses: (None,)}, (None,)), types: ({clump_thickness: tf.int64, cell_size_uniformity: tf.int64, cell_shape_uniformity: tf.int64, marginal_adhesion: tf.int64, single_epithelial_cell_size: tf.int64, bare_nuclei: tf.float64, bland_chromatin: tf.int64, normal_nucleoli: tf.int64, mitoses: tf.int64}, tf.int32)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-27T22:29:48Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/logreg\model.ckpt-5400
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.20325s
INFO:tensorflow:Finished evaluation at 2022-06-27-22:29:48
INFO:tensorflow:Saving dict for global step 5400: accuracy = 0.95, global_step = 5400, loss = 0.16482928
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5400: ./logs/logreg\model.ckpt-5400
{'accuracy': 0.95, 'loss': 0.16482928, 'global_step': 5400}

In [35]:
%load_ext tensorboard
%tensorboard --logdir ./logs/logreg

__Result__

Able to achieve good results (95% Accuracy) in spite of a slightly unbalanced target class.

__Summary__
* Logistic regression predictions are based on the sigmoid curve
* When predicting for a multi-class or multi-label, don't have to use different kinds of One Versus All strategies, just increase the number of nodes to match the number of classes that you have
	- Will use a softmax activation instead

# 4f. Using Non-linear Solutions

More complex models that can potentially model data better. These do not subscribe to 1 coefficient to 1 variable.

__Support Vector Machines (SVM)__

Viable option in terms of random features for large-scale kernel machines. Below leverages Keras to obtain a non-linear solution to a classification problem. The non-linear function applied to the features will be a __Random Fourier Features__ function which approximates kernel-based classifiers and regressors.

In [40]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

# Importing Random Fourier Features function 
try:
    from tensorflow.python.keras.layers.kernelized import RandomFourierFeatures
except:
    from tensorflow.keras.layers.experimental import RandomFourierFeatures

In [43]:
# Define the model - With additional RandomFourierFeatures function for non-linearity
def create_svc(feature_columns, feature_layer_inputs, optimizer, loss='hinge', metrics=['accuracy'], l2=0.01, output_dim=64, scale=None):
	regularizer = keras.regularizers.l2(l2)
 
	feature_layer = keras.layers.DenseFeatures(feature_columns)
	feature_layer_outputs = feature_layer(feature_layer_inputs)
	norm = keras.layers.BatchNormalization()(feature_layer_outputs)
	rff = RandomFourierFeatures(output_dim=output_dim, scale=scale, kernel_initializer='gaussian')(norm)
	outputs = keras.layers.Dense(
		1,
		kernel_initializer='normal',
		kernel_regularizer=regularizer,
		activation='sigmoid'
	)(rff)
 
	model = keras.Model(inputs=[v for v in feature_layer_inputs.values()], outputs=outputs)
	model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
	return model

In [44]:
# Train the model
categorical_cols = []
numeric_cols = ['clump_thickness', 'cell_size_uniformity', 'cell_shape_uniformity',
                'marginal_adhesion', 'single_epithelial_cell_size', 'bare_nuclei', 'bland_chromatin',
                'normal_nucleoli', 'mitoses']

feature_columns, feature_layer_inputs = define_feature_columns_layers(data, categorical_cols, numeric_cols)
optimizer = keras.optimizers.Adam(learning_rate=0.00005)
model = create_svc(feature_columns, feature_layer_inputs, optimizer, loss='hinge', l2=0.001, output_dim=512)
estimator = canned_keras(model, output_dir='./logs/svc')

train_input_fn = make_input_fn(train, y_train, num_epochs=500, batch_size=512)
test_input_fn = make_input_fn(test, y_test, num_epochs=1, shuffle=False)
estimator.train(train_input_fn)
result = estimator.evaluate(test_input_fn)
print(result)

INFO:tensorflow:Using the Keras model provided.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\keras\layers\kernelized.py:187: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Using config: {'_model_dir': './logs/svc', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
<RepeatDataset shapes: ({clump_thickness: (None,), cell_size_uniformity: (None,), cell_shape_uniformity: (None,), marginal_adhesion: (None,), single_epithelial_cell_size: (None,), bare_nuclei: (None,), bland_chromatin: (None,), normal_nucleoli: (None,), mitoses: (None,)}, (None,)), types: ({clump_thickness: tf.int64, cell_size_uniformity: tf.int64, cell_shape_uniformity: tf.int64, marginal_adhesion: tf.int64, single_epithelial_cell_size: tf.int64, bare_nuclei: tf.float64, bland_chromatin: tf.int64, normal_nucleoli: tf.int64, mitoses: tf.int64}, tf.int32)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='./logs/svc\\keras\\keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: ./logs/svc\keras\keras_model.ckpt
INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.
INFO:tensorflow:Warm-started 5 variables.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./logs/svc\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 1.2124147, step = 0
INFO:tensorflow:global_step/sec: 154.559
INFO:tensorflow:loss = 1.0163594, step = 100 (0.648 sec)
INFO:tensorflow:global_step/sec: 226.758
INFO:tensorflow:loss = 0.9262054, step = 200 (0.441 sec)
INFO:tensorflow:global_step/sec: 219.297
INFO:tensorflow:loss = 0.8822274, step = 300 (0.456 sec)
INFO:tensorflow:global_step/sec: 216.92
INFO:tensorflow:loss = 0.8495333, step = 400 (0.462 sec)
INFO:tensorflow:global_step/sec: 215.518
INFO:tensorflow:loss = 0.82440245, step = 500 (0.462 sec)
INFO:tensorflow:global_step/sec: 189.036
INFO:tensorflow:loss = 0.8085748, step = 600 (0.530 sec)
INFO:tensorflow:global_step/sec: 238.662
INFO:tensorflow:loss = 0.7848371, step = 700 (0.418 sec)
INFO:tensorflow:global_step/sec: 238.096
INFO:tensorflow:loss = 0.76742005, step = 800 (0.420 sec)
INFO:tensorflow:global_step/sec: 222.718
INFO:tensorflow:loss = 0.76021, step = 900 (0.451 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1000...
INFO:tensorflow:Saving checkpoints for 1000 into ./logs/svc\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1000...
INFO:tensorflow:Loss for final step: 0.6508977.
<RepeatDataset shapes: ({clump_thickness: (None,), cell_size_uniformity: (None,), cell_shape_uniformity: (None,), marginal_adhesion: (None,), single_epithelial_cell_size: (None,), bare_nuclei: (None,), bland_chromatin: (None,), normal_nucleoli: (None,), mitoses: (None,)}, (None,)), types: ({clump_thickness: tf.int64, cell_size_uniformity: tf.int64, cell_shape_uniformity: tf.int64, marginal_adhesion: tf.int64, single_epithelial_cell_size: tf.int64, bare_nuclei: tf.float64, bland_chromatin: tf.int64, normal_nucleoli: tf.int64, mitoses: tf.int64}, tf.int32)>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-06-27T23:22:09Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/svc\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.23701s
INFO:tensorflow:Finished evaluation at 2022-06-27-23:22:09
INFO:tensorflow:Saving dict for global step 1000: accuracy = 0.95714283, global_step = 1000, loss = 0.7412864
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: ./logs/svc\model.ckpt-1000
{'accuracy': 0.95714283, 'loss': 0.7412864, 'global_step': 1000}

In [46]:

%load_ext tensorboard
%tensorboard --logdir ./logs/svc
%tensorboard dev upload --logdir './logs/svc'

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 5268), started 0:01:27 ago. (Use '!kill 5268' to kill it.)

ERROR: Timed out waiting for TensorBoard to start. It may still be running as pid 15056.

__Result__

Plot is relatively smooth compared ones because of a larger batch. Larger models with more neurons generally perform better with larger batches

__Summary__

* Random Fourier Features helps to mimic the function of SVM kernels (RBF, polynomial, etc.) 
	- able to achieve a lower computational complexity making such an approach feasible for a neural network implementation
* Different non-linear models can be achieved with different loss functions:
	- __Hinge loss__: Sets an SVM model
	- __Logistics loss__: kernel logistic regression (returns class probabilities)
	- __Mean square error__: kernel regression

# 4g. Wide & Deep Models

_Linear models_ are efficient and interpretable because of __memorization__. Linear models record the association between features (or a group of features) into a single coefficient.

_Neural Networks_ are __generalized__ because their complexity is able to approximate general rules that govern the outcome of a process.

__Wide & Deep models__ blend memorization and generalization because they combine a linear model applied to numeric features together with generalization applied to sparse features, such as categories encoded into a sparse matrix. (https://arxiv.org/pdf/1606.07792.pdf)

The model was originally used as a basis for recommendation systems fro the Google Play Store because each "part" of the model handled different types of data. 

* Wide (regression): features relative to user's characteristics (dense numeric features, binary indicators, or combination of interaction features) which are quite consistent
* Deep (neural network): feature strings representing previous software downloads (spares inputs on large matrices), which are more variable over time

Use the Adult datasent, or Census dataset to predict if income exceeds $50K/annum based on the census data. Available features are quite varied, from age to occupation. Feed the different features to the right side of the Wide & Deep model. `tf.estimator.DNNLinearCombinedEstimator`

In [1]:
import tensorflow as tf
import pandas as pd

In [52]:
# Download the dataset and split into train and test sets
census_dir = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/'
train_path = tf.keras.utils.get_file('adult.data', census_dir + 'adult.data')
test_path = tf.keras.utils.get_file('adult.test', census_dir + 'adult.test')

columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
           'marital_status', 'occupation', 'relationship', 'race', 'gender',
           'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
           'income_bracket']

train_data = pd.read_csv(train_path, header=None, names=columns)
test_data = pd.read_csv(test_path, header=None, names=columns, skiprows=1)
train_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income_bracket
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [53]:
train_data.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [54]:
# Select a subset of features to be used for model
predictors = ['age', 'workclass', 'education', 'education_num', 'marital_status', 
			  'occupation', 'relationship', 'gender']

# Change the target variable to integer
y_train = (train_data['income_bracket'] == ' >50K').astype(int)
y_test = (test_data['income_bracket'] == ' >50K.').astype(int)

train_data = train_data[predictors]
test_data = test_data[predictors]

# Replace missing values with a mean value
train_data[['age', 'education_num']] = train_data[['age', 'education_num']].fillna(train_data[['age', 'education_num']].mean())
test_data[['age', 'education_num']] = test_data[['age', 'education_num']].fillna(train_data[['age', 'education_num']].mean())

In [58]:
# Functions that deal with the interaction of categorical and numeric columns
def define_feature_columns(data_df, numeric_cols, categorical_cols, embedded_cols, dims=30):
	num_cols = []
	cat_cols = []
	embeddings = []
	
	for feature_name in numeric_cols:
		num_cols.append(tf.feature_column.numeric_column(feature_name, dtype=tf.float32))
	for feature_name in categorical_cols:
		vocabulary = data_df[feature_name].unique()
		cat_cols.append(tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary))
	for feature_name in embedded_cols:
		vocabulary = data_df[feature_name].unique()
		to_categorical = tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary)
		embeddings.append(tf.feature_column.embedding_column(to_categorical, dimension=dims))
	
	return num_cols, cat_cols, embeddings
	
# Function to create interaction terms between variables of all types
def create_interactions(interactions_list, buckets=10):
    feature_columns = []
    
    for (a, b) in interactions_list:
        crossed_feature = tf.feature_column.crossed_column([a, b], hash_bucket_size=buckets)
        crossed_feature_one_hot = tf.feature_column.indicator_column(crossed_feature)
        feature_columns.append(crossed_feature_one_hot)

    return feature_columns

In [59]:
# Map different columns and add meaninful interactions - to create final list of features
numeric_cols, categorical_cols, embedding_cols = define_feature_columns(train_data,
                                                                       ['age', 'education_num'],
                                                                       ['gender'],
                                                                       ['workclass', 'education', 'marital_status', 'occupation', 'relationship'],
                                                                       dims=32)
                                                                       # mapping high-dimensional categorical features into fixed lower dimensional numeric space of 32
interactions = create_interactions([['education', 'occupation']], buckets=10)

In [61]:
# Model
estimator = tf.estimator.DNNLinearCombinedClassifier(
	# wide settings
	linear_feature_columns=numeric_cols + categorical_cols + interactions,
	linear_optimizer=tf.keras.optimizers.Ftrl(0.0002),
	# deep settings
	dnn_feature_columns=embedding_cols,
	dnn_hidden_units=[1024, 256, 128, 64],
	dnn_optimizer=tf.keras.optimizers.Adagrad(0.0001),
	model_dir='./logs/wd'
)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './logs/wd', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [62]:
def make_input_fn(data_df, label_df, num_epochs=10, shuffle=True, batch_size=256):
    def input_function():
        ds = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))
        if shuffle:
            ds = ds.shuffle(1000)
        ds = ds.batch(batch_size).repeat(num_epochs)
        return ds
    
    return input_function

In [63]:
# Train estimator
train_input_fn = make_input_fn(train_data, y_train, num_epochs=100, batch_size=256)
test_input_fn = make_input_fn(test_data, y_test, num_epochs=1, shuffle=False)

estimator.train(input_fn=train_input_fn, steps=1500)
results = estimator.evaluate(input_fn=test_input_fn)
print(results)

WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\training\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\feature_column\feature_column_v2.py:540: Layer.add_variable (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.add_weight` method instead.
WARNING:tensorflow:From c:\Users\Martin Ho\Languages\python368\lib\site-packages\tensorflow\python\keras\optimizer_v2\adagrad.py:106: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./logs/wd\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.70521426, step = 0
INFO:tensorflow:global_step/sec: 25.7998
INFO:tensorflow:loss = 0.6665188, step = 100 (3.876 sec)
INFO:tensorflow:global_step/sec: 29.949
INFO:tensorflow:loss = 0.6572366, step = 200 (3.344 sec)
INFO:tensorflow:global_step/sec: 29.9492
INFO:tensorflow:loss = 0.635617, step = 300 (3.335 sec)
INFO:tensorflow:global_step/sec: 29.6208
INFO:tensorflow:loss = 0.6407486, step = 400 (3.386 sec)
INFO:tensorflow:global_step/sec: 28.3045
INFO:tensorflow:loss = 0.6175965, step = 500 (3.534 sec)
INFO:tensorflow:global_step/sec: 30.9886
INFO:tensorflow:loss = 0.6123662, step = 600 (3.216 sec)
INFO:tensorflow:global_step/sec: 29.9311
INFO:tensorflow:loss = 0.608737, step = 700 (3.340 sec)
INFO:tensorflow:global_step/sec: 30.2203
INFO:tensorflow:loss = 0.6114052, step = 800 (3.311 sec)
INFO:tensorflow:global_step/sec: 30.9788
INFO:tensorflow:loss = 0.5910848, step = 900 (3.227 sec)
INFO:tensorflow:global_step/sec: 30.5722
INFO:tensorflow:loss = 0.6138073, step = 1000 (3.271 sec)
INFO:tensorflow:global_step/sec: 34.4234
INFO:tensorflow:loss = 0.61214936, step = 1100 (2.905 sec)
INFO:tensorflow:global_step/sec: 28.4576
INFO:tensorflow:loss = 0.59169877, step = 1200 (3.514 sec)
INFO:tensorflow:global_step/sec: 30.6279
INFO:tensorflow:loss = 0.63031197, step = 1300 (3.265 sec)
INFO:tensorflow:global_step/sec: 31.6256
INFO:tensorflow:loss = 0.66148597, step = 1400 (3.162 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1500...
INFO:tensorflow:Saving checkpoints for 1500 into ./logs/wd\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1500...
INFO:tensorflow:Loss for final step: 0.6072451.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-07-06T00:32:30Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs/wd\model.ckpt-1500
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 3.97196s
INFO:tensorflow:Finished evaluation at 2022-07-06-00:32:34
INFO:tensorflow:Saving dict for global step 1500: accuracy = 0.76377374, accuracy_baseline = 0.76377374, auc = 0.31664154, auc_precision_recall = 0.16444652, average_loss = 0.59362483, global_step = 1500, label/mean = 0.23622628, loss = 0.5936036, precision = 0.0, prediction/mean = 0.3465339, recall = 0.0
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1500: ./logs/wd\model.ckpt-1500
{'accuracy': 0.76377374, 'accuracy_baseline': 0.76377374, 'auc': 0.31664154, 'auc_precision_recall': 0.16444652, 'average_loss': 0.59362483, 'label/mean': 0.23622628, 'loss': 0.5936036, 'precision': 0.0, 'prediction/mean': 0.3465339, 'recall': 0.0, 'global_step': 1500}

__Result__

Decent results, but could be better with more tuning

__Summary__

Wide & Depp models represent a way to handle linear models together with more complex approaches involving neural networks. They are usually used for recommendation systems where there are multiple features of different data types, and therefore require different methods to feed into the model.

Estimators are straightfoward and easy to use. They are also efficient, and provide out of the box models to quickly deploy various ML algorithms. Bulk of the work is done by defining an input data function and mapping the features with more suitable functions from `tf.feature_columns`